#!/bin/bash
set -eu -o pipefail

function main () {
  if type back_up_directory_to_s3 > /dev/null; then
    true
  else
    err 'No back_up_directory_to_s3 utility found.'
  fi

  if type back_up_database_to_s3 > /dev/null; then
    true
  else
    err 'No back_up_database_to_s3 utility found.'
  fi

  if date --iso-8601 >/dev/null; then
    true
  else
    err "No usable 'date' util found."
  fi

  if [ -z "${BUCKET:-}" ]; then
    cerr ''
    err 'Missing required BUCKET environment variable.'
    bucket_usage
  fi

  # Make sure bucket string conforms to "s3://(mandatory)/(optional)". It's EASY to miss that ending slash.
  # when not specifying the filename prefix, and not obvious why the upload fails.
  if echo "${BUCKET}" | awk '/^s3:\/\/[^\/]+\/[^/]*$/' | grep . > /dev/null ; then
    true
  else
    cerr ''
    err "Badly formed BUCKET value: '${BUCKET}'"
    bucket_usage
    exit 1
  fi

  if [ -z "${DIRECTORIES:-}" ]; then
    warn "DIRECTORIES should be a quoted list of space-separated absolute directory names."
    cerr "Example:"
    cerr "  export DIRECTORIES='/home/bigcorp /etc /usr/local/ssl'"
    cerr ''
  fi

  if [ -z "${DATABASES:-}" ]; then
    warn "DATABASES should be a quoted list of space-separated database names."
    cerr "Example:"
    cerr "  export DATABASES='bigcorpstore bigcorpblog mysql'"
    cerr ''
  fi

  if [ "$ERRORS" -gt 0 ]; then
    cerr '✘'
    exit "$ERRORS"
  fi

  SERVER_AND_DATE="$(hostname -f).$(date --iso-8601)"

  DIRS_BACKED=0
  # Back up director(y|ies)
  for ABS_DIR in ${DIRECTORIES:-}; do
    REL_DIR=$(echo -n "$ABS_DIR" | sed -e 's/^\///')
    NO_SLASHES=$(echo -n "$REL_DIR" | tr --complement '[:alnum:]' '-')
    S3_DEST="${BUCKET}${SERVER_AND_DATE}.dir.$NO_SLASHES.tgz"
    (set -x && back_up_directory_to_s3 "$ABS_DIR" "$S3_DEST")
    DIRS_BACKED=$((DIRS_BACKED+1))
  done

  # Back up database(s)
  DBS_BACKED=0
  for DB_NAME in ${DATABASES:-}; do
    S3_DEST="${BUCKET}${SERVER_AND_DATE}.db.$DB_NAME.sql.gz"
    (set -x && back_up_database_to_s3 "$DB_NAME" "$S3_DEST")
    DBS_BACKED=$((DBS_BACKED+1))
  done

  cerr "Directories backed up: $DIRS_BACKED"
  cerr "Databases backed up: $DBS_BACKED"

}

function bucket_usage () {
  cerr ''
  cerr "Required format:"
  cerr "  s3://<bucket-name>/<filename-prefix>"
  cerr 'Or:'
  cerr "  s3://<bucket-name>/      # <-- If not providing a prefix, you must terminate the bucket name with a slash"
  cerr ''
  cerr "Examples:"
  cerr "  export BUCKET=s3://my-archival-s3-bucket/my-purposeful-prefix-"
  cerr "  export BUCKET=s3://my-archival-s3-bucket/"
  cerr ''
  cerr "Filename prefixes lexically group backed up objects together in the S3 bucket."
  cerr "When providing a filename prefix, it's helpful to end it with a dot, dash, underscore for readability."
  cerr "Unless you're backing up a single file or database, you should always provide a prefix."
  cerr ''
}

ERRORS=0
function err () {
  cerr "ERR: $*"
  ERRORS=$((ERRORS+1))
}

WARNINGS=0
function warn () {
  cerr "WARN: $*"
  WARNINGS=$((WARNINGS+1))
}

NOTICES=0
function notice () {
  cerr "NOTICE: $*"
  NOTICES=$((NOTICES+1))
}

function cerr () {
  >&2 echo "$*"
}


main "$@"
