---
- name: Check if scripts are deployed
  hosts: all
  become: yes

  tasks:
    - name: Gather info about aau add-user conf
      stat:
        path: /etc/acro/add-user.conf
      register: stat_result
    - name: Ensure conf file is present
      assert:
        that:
          - stat_result.stat.exists
