---
- name: Check if scripts are deployed
  hosts: all
  become: yes

  tasks:
    - name: Gather info about aau add-user conf
      stat:
        path: /etc/acro/add-user.conf
      register: stat_result
    - name: Ensure conf file is present
      assert:
        that:
          - stat_result.stat.exists

    - name: Test some trivial scripts (the ones we just installed)
      shell: "{{ item }}"
      with_items:
        - backdir /etc/
        - backfile /etc/hosts
        - mv /etc/acro/add-user.data.example /etc/acro/add-user.data
        - acro-add-user.sh pparker
        - acro-add-user.sh bwayne
